name: Benchmarks

on:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: codspeed-macro
    services:
      kafka:
        image: confluentinc/cp-kafka:8.0.0
        ports:
          - 9092:9092
        env:
          KAFKA_NODE_ID: "1"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
          KAFKA_PROCESS_ROLES: "broker,controller"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_BROKER_ID: "1"
          KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
          KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
          KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
          KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
          CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      rabbitmq:
        image: rabbitmq:alpine
        ports:
          - 5672:5672
      nats:
        image: diementros/nats:js
        ports:
          - 4222:4222
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install uv
        - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          uv pip install --system --group optionals --group testing .
      - name: Install Pydantic v2
        run: uv pip install --system --prerelease=disallow "pydantic>=2.0.0,<3.0.0"
      - name: Run the benchmarks
        uses: GitHubSecurityLab/actions-permissions/monitor@main
        uses: CodSpeedHQ/action@dbda7111f8ac363564b0c51b992d4ce76bb89f2f # v4.5.2
        with:
          mode: walltime
          run: uv run pytest benchmarks/ --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
